services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d 
    healthcheck:
      test: "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1"
      interval: 10s
      retries: 10
    entrypoint: /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 20 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P YourStrong@Passw0rd -i /docker-entrypoint-initdb.d -C &&
      wait"
    networks:
      - app-network

  api:
    build: ../.
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__HangfireConnection=Server=sqlserver;Database=HangfireTest;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    networks:
      - app-network

networks:
  app-network:

volumes:
  sqlserver-data: